#!/usr/bin/env bash
# Fetch steward-gateway's GraphQL SDL at the commit pinned in schema-refs.env,
# assemble it into schema/gateway.graphql, record its SHA-256 in schema-refs.env,
# then regenerate the typed operations in src/generated/. Run after changing
# STEWARD_GATEWAY_REF, or after editing an operation in src/operations/.
#
# The only network step is the fetch. CI never runs this script; it runs
# scripts/schema-check.sh, which checks the committed copy offline.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# shellcheck source=/dev/null
source schema-refs.env

if [[ ! "${STEWARD_GATEWAY_REF}" =~ ^[0-9a-f]{40}$ ]]; then
  echo "schema-generate: STEWARD_GATEWAY_REF must be a full 40-character commit sha." >&2
  exit 1
fi

repo="${STEWARD_GATEWAY_REPO:-https://github.com/Steward-GRC/steward-gateway.git}"
work="$(mktemp -d)"
trap 'rm -rf "${work}"' EXIT

echo "schema-generate: fetching steward-gateway graphql/ at ${STEWARD_GATEWAY_REF}."
git -C "${work}" init -q
git -C "${work}" fetch -q --depth 1 "${repo}" "${STEWARD_GATEWAY_REF}"

mapfile -t files < <(git -C "${work}" ls-tree --name-only FETCH_HEAD graphql/ | grep '\.graphqls$' | LC_ALL=C sort)
if [ "${#files[@]}" -eq 0 ]; then
  echo "schema-generate: no graphql/*.graphqls at ${STEWARD_GATEWAY_REF}." >&2
  exit 1
fi

# schema.graphqls declares the root types the other files extend, so it goes first.
ordered=()
for f in "${files[@]}"; do
  [ "${f}" = "graphql/schema.graphqls" ] && ordered+=("${f}")
done
for f in "${files[@]}"; do
  [ "${f}" != "graphql/schema.graphqls" ] && ordered+=("${f}")
done

out="schema/gateway.graphql"
{
  echo "# Generated by packages/api-client/scripts/schema-generate.sh. Do not edit."
  echo "# Source: steward-gateway graphql/*.graphqls"
  echo "# steward-gateway commit: ${STEWARD_GATEWAY_REF}"
  for f in "${ordered[@]}"; do
    echo
    echo "# ---- ${f}"
    git -C "${work}" show "FETCH_HEAD:${f}"
  done
} >"${out}"

sum="$(sha256sum "${out}" | cut -d' ' -f1)"
sed -i -E "s/^STEWARD_GATEWAY_SCHEMA_SHA256=.*/STEWARD_GATEWAY_SCHEMA_SHA256=${sum}/" schema-refs.env
echo "schema-generate: wrote ${out} (${#ordered[@]} files, sha256 ${sum})."

pnpm exec graphql-codegen --config codegen.ts
